default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: fudisturnaus

test:
  <<: *default
  database: fudisturnaus_test

# On Heroku, the DATABASE_URL environment variable takes precedence.
production:
  <<: *default
